# Generated by Django 2.2.1 on 2020-05-12 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='rus',
            new_name='name',
        ),
    ]
